#!/bin/bash
# Automagically generated by Breeze ( $url )
# Generated $date ($tz)
# Generated by $user
# Target is $target

# Non language specific, non target specific, job bootstrap configuration file
# breeze run_job_conf.sh version 0.1.1 clement.fiere@helsinki.fi 06/10/2016
# Configuration variables, parsed and filled from Breeze
LOG_FOLDER="$log_folder"
FAILED_FN="$failed_fn"
INCOMPLETE_FN="$inc_run_fn"
SUCCESS_FN="$success_fn"
DONE_FN="$done_fn"
IN="$in_file_name"
OUT=${IN}".Rout"
# OUT="$out_file_name"
EXEC_PATH="$full_path"
EXEC_ARGS="$args"
EXEC_CMD="$cmd"
RUN_LINE=${EXEC_PATH}" "${EXEC_CMD}
FAILED_TEXT="$failed_txt"
POKE_URL="$poke_url"
TARGET="$target"
ENGINE_NAME="$engine"
ARCH=$arch_cmd
EXEC_VERSION=$version_cmd
# TOTAL_MEM=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
TOTAL_MEM=$(getconf -a | grep PAGES | awk 'BEGIN {total = 1} {if (NR == 1 || NR == 3) total *=$NF} END {print total / 1024^3" GiBi"}')
LOG_CORES=$([[ $(uname) = 'Darwin' ]] && sysctl -n hw.logicalcpu_max || lscpu -p | egrep -v '^#' | wc -l)
PHY_CORES=$([[ $(uname) = 'Darwin' ]] && sysctl -n hw.physicalcpu_max || lscpu -p | egrep -v '^#' | sort -u -t, -k 2,4 | wc -l)
### ENV SPECIFIC ###
export _JAVA_OPTIONS=-Xmx4096m
## END OF CONFIGURATION
