#!/bin/bash
# Automagically generated by Breeze ( $url )
# Generated $date ($tz)
# Generated by $user
# Target is $target

# Non language specific, non target specific, job bootstrap file
# breeze run_job.sh version 0.3.2 clement.fiere@helsinki.fi 20/12/2016
# compatible with :
# 	compute targets : sge, docker
# 	language 	: R (possibly others)
source $conf_file
export AZURE_KEY='' # FIXME hack
RELEASE='/etc/os-release'
if [ -f "$RELEASE" ];
then
	source ${RELEASE}
else
	PRETTY_NAME='N/A'
fi
# Info messages
echo 'host    : '`hostname`' @ '`hostname -i`
echo 'os      : '${PRETTY_NAME}
echo 'kernel  : '`uname -mrs`
echo 'arch    : '${ARCH}
echo 'CPU     : '${LOG_CORES}' / '${PHY_CORES}' (logical / physical)'
echo 'memory  : '${TOTAL_MEM}
echo 'dir     : '`pwd`
echo 'target  : '${TARGET}
echo 'engine  : '${ENGINE_NAME}
echo 'version : '${EXEC_VERSION}
echo 'command : '${RUN_LINE}
echo '######################################################### ENV #########################################################'
env
echo '######################################################### END #########################################################'
echo
# removing possibly existing files generated from a previous run
rm *~ ${OUT} ${FAILED_FN} ${INCOMPLETE_FN} ${SUCCESS_FN} ${DONE_FN} > /dev/null 2>&1
wget -qO- ${POKE_URL}'starting' > /dev/null
echo `date --rfc-3339=second | sed 's/ /T/'`
echo -n 'Running '${IN}'...'
# Running the job
touch ./${INCOMPLETE_FN} && `${RUN_LINE}`
CODE=$?
echo ' done !'
if [ ${CODE} -eq 0 ];
then
	touch ./${SUCCESS_FN}
fi
echo `date --rfc-3339=second | sed 's/ /T/'`
# Removes incomplete run file flag
rm ./${INCOMPLETE_FN} > /dev/null 2>&1
CMD=`tail -n1<./${OUT}`
# check the last line of the Rout file for possible job internal failure
if [ "$CMD" = "$FAILED_TEXT" ] || [ ! -f "$DONE_FN" ];
then
	touch ./${FAILED_FN}
	# cat ${OUT}
	echo 'Failure !'
	wget -qO- ${POKE_URL}'failed/'${CODE} > /dev/null
	exit ${CODE}
else
	wget -qO- ${POKE_URL}'success' > /dev/null
	echo 'Success !'
fi
# removes any possible temp file (we don't want them to be part of the resulting folder)
rm *~ > /dev/null 2>&1
exit 0
